"""
Interpretation domain model.

Represents the structured clinical interpretation
generated by the reasoning engine.
"""

from dataclasses import dataclass, field

from .finding import Finding
from .match_result import MatchResult


@dataclass(frozen=True, slots=True)
class Interpretation:
    """
    Final structured interpretation.

    This object is consumed by the AI layer.
    """

    findings: tuple[Finding, ...] = field(default_factory=tuple)

    matches: tuple[MatchResult, ...] = field(default_factory=tuple)

    primary_match: MatchResult | None = None